.PHONY: generate-keypair read-data-from-solana check-balance create_tx_on_solana transfer using-custom-onchain-programs send-ping-transaction interact-with-wallets

generate-keypair:
	pnpx esrun ./scripts/generate-keypair.ts

read-data-from-solana:
	pnpx esrun ./scripts/read-data-from-solana.ts

check-balance:
	pnpx esrun ./scripts/check-balance.ts

create_tx_on_solana:
	pnpx esrun ./scripts/create_tx_on_solana.ts

transfer:
	pnpx esrun ./scripts/transfer.ts HU4W3Ra2UMCsBGXRdveHQeLNVtPbNGLBDkvbAhVDEwXr

using-custom-onchain-programs:
	pnpx esrun ./scripts/using-custom-onchain-programs.ts
send-ping-transaction:
	pnpx esrun ./scripts/send-ping-transaction.ts

interact-with-wallets:
	pnpx esrun ./scripts/interact-with-wallets.ts
