.PHONY: generate-keypair read-data-from-solana check-balance create_tx_on_solana

generate-keypair:
	pnpx esrun ./scripts/generate-keypair.ts

read-data-from-solana:
	pnpx esrun ./scripts/read-data-from-solana.ts

check-balance:
	pnpx esrun ./scripts/check-balance.ts

create_tx_on_solana:
	pnpx esrun ./scripts/create_tx_on_solana.ts